name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
repository: https://github.com/baseflow/flutter-permission-handler
issue_tracker: https://github.com/Baseflow/flutter-permission-handler/issues
version: 10.4.3

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android
      ios:
        default_package: permission_handler_apple
      windows:
        default_package: permission_handler_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  permission_handler_android:
    git:
      url: git@github.com:ibrahimMahfuz/flutter-permission-handler.git
      path: permission_handler_android
      ref: test
  permission_handler_apple:
    git:
      url: git@github.com:ibrahimMahfuz/flutter-permission-handler.git
      path: permission_handler_apple
      ref: test
  permission_handler_windows:
    git:
      url: git@github.com:ibrahimMahfuz/flutter-permission-handler.git
      path: permission_handler_windows
      ref: test
  permission_handler_platform_interface:
    git:
      url: git@github.com:ibrahimMahfuz/flutter-permission-handler.git
      path: permission_handler_platform_interface
      ref: test

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  plugin_platform_interface: ^2.0.0
