name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
repository: https://github.com/baseflow/flutter-permission-handler
issue_tracker: https://github.com/Baseflow/flutter-permission-handler/issues
version: 11.3.1


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  permission_handler_android:
    path: /Users/segari/code/mobile/flutter-permission-handler/permission_handler_android
  permission_handler_platform_interface:
    path: /Users/segari/code/mobile/flutter-permission-handler/permission_handler_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4
  plugin_platform_interface: ^1.0.3
